name: php-cs-fixer

on:
  push:
  pull_request:

jobs:
  laravel-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0"
      - name: Prepare
        run: |
          mkdir --parents tools/php-cs-fixer
          composer require --working-dir=tools/php-cs-fixer friendsofphp/php-cs-fixer
      - name: php-cs-fixer
        run: tools/php-cs-fixer/vendor/bin/php-cs-fixer fix ./ --dry-run --diff --diff-format=udiff --using-cache=no
